version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy


  db:
    container_name: health_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 2231218/m
      MYSQL_DATABASE: health_db
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  redis:
    container_name: redis
    image: redis:7.0
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  my-db:
