Server:
  Host: localhost
  Port: 8080
  Environment: dev # dev, prod

MySQL:
  Host: 127.0.0.1
  Port: 3306
  User: root
  Pass: 2231218/m
  Database: health_db

Redis:
  Host: localhost
  Port: 6379
  User:
  Pass:

Webhook:
  URL: localhost
  Method: POST # get, post
  Timeout: 30 # in seconds

