Server:
  Host: localhost # for docker to use in mac put: host.docker.internal
  Port: 8080
  Environment: dev # dev, prod

MySQL:
  Host: db
  Port: 3306 #3306
  User: root
  Pass: 2231218/m
  Database: health_db

Redis:
  Host: redis
  Port: 6379 # 6379
  User:
  Pass:

Webhook:
  URL: http://localhost:8000/test-webhook
  Method: POST # get, post
  Timeout: 30s

Service:
  Cache: redis # memory